application:
  datasource:
    url: jdbc:mysql://172.24.246.243:3306/groot-tools?serveTimezone=GMT
    username: root
    password: Swt620523
  redis:
    host: 172.24.246.243
    port: 6379
  sa-token:
    jwt-secret-key: hqiou12wehio43uwe3487hfiouawhefoia
