application:
  datasource:
    url: jdbc:mysql://localhost:3306/groot-tools?serveTimezone=GMT
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
  sa-token:
    jwt-secret-key: 123456
