# 应用配置
application:
  # 数据库配置
  datasource:
    # 数据库URL
    url: jdbc:mysql://localhost:3306/groot-tools?serveTimezone=GMT
    # 数据库账号
    username: root
    # 数据库密码
    password: 123456
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    
