application:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/groot-tools?serveTimezone=GMT
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
  sa-token:
    jwt-secret-key: 123456
  mail:
    host: xxx
    port: xxx
    password: xxx
    username: xxx